version: '2'
services:
  # postgresql12:
  #   image: postgres:13.4-alpine
  #   volumes:
  #   - ./pg12data:/var/lib/postgresql/data
  #   ports:
  #   - 5432:5432
  #   environment:
  #   - POSTGRES_USER=postgres
  #   - POSTGRES_PASSWORD="qT85Hwg"
  #   - POSTGRES_DB=monitor
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    # depends_on: 
    #   - postgresql12