# Generated by Django 4.2 on 2023-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ubicacion",
            name="nivel",
            field=models.IntegerField(default="0"),
            preserve_default=False,
        ),
    ]
