# Generated by Django 4.2 on 2023-04-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acervos", "0007_remove_fisicaimagen_ubicacion"),
        ("catalogos", "0002_ubicacion_nivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ubicacion",
            name="imagenes",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ubicaciones",
                to="acervos.visualimagen",
            ),
            preserve_default=False,
        ),
    ]
