# Generated by Django 4.2 on 2023-04-24 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acervos", "0002_acervocliente_autor_editor_licenciatipo_personaje_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contenedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tn_ancestors_pks",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Ancestors pks",
                    ),
                ),
                (
                    "tn_ancestors_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Ancestors count"
                    ),
                ),
                (
                    "tn_children_pks",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Children pks",
                    ),
                ),
                (
                    "tn_children_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Children count"
                    ),
                ),
                (
                    "tn_depth",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Depth",
                    ),
                ),
                (
                    "tn_descendants_pks",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Descendants pks",
                    ),
                ),
                (
                    "tn_descendants_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Descendants count"
                    ),
                ),
                (
                    "tn_index",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Index"
                    ),
                ),
                (
                    "tn_level",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Level",
                    ),
                ),
                (
                    "tn_priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                (
                    "tn_order",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Order"
                    ),
                ),
                (
                    "tn_siblings_pks",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Siblings pks",
                    ),
                ),
                (
                    "tn_siblings_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Siblings count"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("estatus", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "tn_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tn_children",
                        to="acervos.contenedor",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acervo",
                "verbose_name_plural": "Acervos",
                "ordering": ["tn_order"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(name="acervo", options={},),
        migrations.RemoveField(model_name="acervo", name="nombre",),
        migrations.RemoveField(model_name="acervo", name="tn_ancestors_count",),
        migrations.RemoveField(model_name="acervo", name="tn_ancestors_pks",),
        migrations.RemoveField(model_name="acervo", name="tn_children_count",),
        migrations.RemoveField(model_name="acervo", name="tn_children_pks",),
        migrations.RemoveField(model_name="acervo", name="tn_depth",),
        migrations.RemoveField(model_name="acervo", name="tn_descendants_count",),
        migrations.RemoveField(model_name="acervo", name="tn_descendants_pks",),
        migrations.RemoveField(model_name="acervo", name="tn_index",),
        migrations.RemoveField(model_name="acervo", name="tn_level",),
        migrations.RemoveField(model_name="acervo", name="tn_order",),
        migrations.RemoveField(model_name="acervo", name="tn_parent",),
        migrations.RemoveField(model_name="acervo", name="tn_priority",),
        migrations.RemoveField(model_name="acervo", name="tn_siblings_count",),
        migrations.RemoveField(model_name="acervo", name="tn_siblings_pks",),
        migrations.RemoveField(model_name="licencia", name="AcervoCliente",),
        migrations.AddField(
            model_name="acervo",
            name="name",
            field=models.TextField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fisicaimagen",
            name="acervo",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="acervos.acervo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licencia",
            name="Acervo",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="acervos.acervo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualimagen",
            name="titulo_origen",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="AcervoCliente",),
        migrations.AlterField(
            model_name="fisicaimagen",
            name="contenedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="acervos.contenedor"
            ),
        ),
    ]
