# Generated by Django 4.2 on 2023-04-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
        (
            "acervos",
            "0003_contenedor_alter_acervo_options_remove_acervo_nombre_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fisicaimagen",
            name="ubicacion",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogos.ubicacion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualimagen",
            name="ubicacion",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogos.ubicacion",
            ),
            preserve_default=False,
        ),
    ]
