# Generated by Django 4.2 on 2023-04-24 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0004_remove_ubicacion_imagenes"),
        ("acervos", "0007_remove_fisicaimagen_ubicacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualimagen",
            name="ubicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imagenes",
                to="catalogos.ubicacion",
            ),
        ),
    ]
