# Generated by Django 4.2 on 2023-04-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acervos", "0008_alter_visualimagen_ubicacion"),
    ]

    operations = [
        migrations.DeleteModel(name="Autor",),
        migrations.DeleteModel(name="Editor",),
        migrations.RemoveField(model_name="licencia", name="Acervo",),
        migrations.RemoveField(model_name="licencia", name="VisualImagenes",),
        migrations.RemoveField(model_name="licencia", name="tipo_licencia",),
        migrations.DeleteModel(name="Personaje",),
        migrations.DeleteModel(name="Licencia",),
        migrations.DeleteModel(name="LicenciaTipo",),
    ]
