# Generated by Django 4.2 on 2023-04-19 21:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acervos", "0003_acervo_level_acervo_lft_acervo_parent_acervo_rght_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acervo",
            options={
                "ordering": ["tn_order"],
                "verbose_name": "Acervo",
                "verbose_name_plural": "Acervos",
            },
        ),
        migrations.RemoveField(model_name="acervo", name="level",),
        migrations.RemoveField(model_name="acervo", name="lft",),
        migrations.RemoveField(model_name="acervo", name="parent",),
        migrations.RemoveField(model_name="acervo", name="rght",),
        migrations.RemoveField(model_name="acervo", name="tree_id",),
        migrations.AddField(
            model_name="acervo",
            name="tn_ancestors_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Ancestors count"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_ancestors_pks",
            field=models.TextField(
                blank=True, default="", editable=False, verbose_name="Ancestors pks"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_children_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Children count"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_children_pks",
            field=models.TextField(
                blank=True, default="", editable=False, verbose_name="Children pks"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_depth",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Depth",
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_descendants_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Descendants count"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_descendants_pks",
            field=models.TextField(
                blank=True, default="", editable=False, verbose_name="Descendants pks"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_index",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Index"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_level",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Level",
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_order",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Order"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tn_children",
                to="acervos.acervo",
                verbose_name="Parent",
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_priority",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Priority",
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_siblings_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Siblings count"
            ),
        ),
        migrations.AddField(
            model_name="acervo",
            name="tn_siblings_pks",
            field=models.TextField(
                blank=True, default="", editable=False, verbose_name="Siblings pks"
            ),
        ),
    ]
