# Generated by Django 4.2 on 2023-04-20 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acervos", "0004_alter_acervo_options_remove_acervo_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcervoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("estatus", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LicenciaTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("estatus", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(model_name="fisicaimagen", name="nombre",),
        migrations.RemoveField(model_name="fisicaimagen", name="visual",),
        migrations.RemoveField(model_name="visualimagen", name="nombre",),
        migrations.AddField(
            model_name="fisicaimagen",
            name="contenedor",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="acervos.acervo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fisicaimagen",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fisicaimagen",
            name="titulo",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visualimagen",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="visualimagen",
            name="titulo",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fisicaimagen",
            name="estatus",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="visualimagen",
            name="estatus",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Licencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.DateTimeField(auto_now_add=True)),
                (
                    "AcervoCliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acervos.acervocliente",
                    ),
                ),
                ("VisualImagenes", models.ManyToManyField(to="acervos.visualimagen")),
                (
                    "tipo_licencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acervos.licenciatipo",
                    ),
                ),
            ],
        ),
    ]
