# Generated by Django 4.2 on 2023-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acervos", "0005_alter_contenedor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acervo", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="licenciatipo",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
